name: "Sample English G2P"  # This is the model name shown in the dropdown

# Specify the path of the onnx file or `auto` to use the files inside of this folder, also don't use backward slashes
onnx: "auto"
dict: "auto"  

graphemes: 
  ["", "", "", "", "'", "-", "a", "b", "c", "d", "e",
                 "f", "g", "h", "i", "j", "k", "l", "m", "n", "o", "p",
                 "q", "r", "s", "t", "u", "v", "w", "x", "y", "z",
                 "A", "B", "C", "D", "E",
                 "F", "G", "H", "I", "J", "K", "L", "M", "N", "O", "P",
                 "Q", "R", "S", "T", "U", "V", "W", "X", "Y", "Z"]

phonemes: 
  ["", "", "", "", "aa", "ae", "ah", "ao", "aw", "ax", "ay", "b", "ch",
                "d", "dh", "dr", "dx", "eh", "er", "ey", "f", "g", "hh", "ih", "iy", "jh",
                "k", "l", "m", "n", "ng", "ow", "oy", "p", "q", "r", "s", "sh", "t",
                "th", "tr", "uh", "uw", "v", "w", "y", "z", "zh"]
